services:
  - type: web
    name: fullstack-javascript-project-6
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: SESSION_SECRET
        value: "this-is-a-very-long-and-secure-session-secret-key-12345" 