services:
  - type: web
    name: task-manager
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString

databases:
  - name: task-manager-db
    plan: free 