services:
  - type: web
    name: your-app-name
    env: python # или node, ruby и т.д.
    buildCommand: pip install -r requirements.txt # или npm install
    startCommand: python app.py # или npm start
    envVars:
      - key: PORT
        value: 8000 