services:
  - type: web
    name: fullstack-javascript-project-6
    env: node
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: SESSION_KEY
        value: "VGhpc0lzQVZlcnlTZWN1cmVLZXlGb3JTZXNzaW9uMTIzNDU2Nzg5"